purchase_type: on_demand
subnet_id: subnet-ea6b468e
price: 0.08
num_instances: 3
key_name: george-lu
security_group_ids: sg-6d46ad14
instance_type: m4.large
tag_name: george-cluster
vol_size: 160
role: worker
use_eips: true
